### ISSUE TITLE
Change name of fixed children

### ISSUE THREAD

**Issue by j-era** [artcom/acms-ui#1]
Would be nice to add the possibility to change the name of a "fixedChildren". Only can do that by creating another template with a different "name" key, right?

```
{
  "fixedChildren": [
    {
      "id": "0",
      "name": "NameToChange",
      "template": "templateC"
    }
  ]
}
```

**Comment by xadh00m** [comment]
Yes. This is a static property. What is your use case here?

**Comment by j-era** [comment]
I'd like to reuse a template, but change the name field dynamically. It might be helpful to show explicit children names in the UI.

**Comment by xadh00m** [comment]
This can be patially done with the subtitle feature desccribed in the README.md.
